# only used when use_hpo: true
n_combinations: 9

# Specify single value, list of values or range e.g.
# single value use
# batch_size: 32
# OR a list of values
# batch_size: 
#   - 4
#   - 128
# OR a range specify the min and max values
# batch_size:
#   - 16
#   - 128
batch_size: 
  min: 8
  max: 64

do_cropping: false
# x and y cropping position
cropping_position:
  - 40
  - 10

# Specify single value or range
n_epochs: 50
# Specify single value or range
patience: 20

# Specify single value or range
learning_rate: 
  min: 0.0001
  max: 0.01

# Specify single value or range
momentum:
  - 0.5
  - 0.9
  - 0.99

# Specify single value or range
nesterov:
  - true
  - false

# Specify single value or range
architecture_name:
  - InceptionV3
